export const PROJECTION_MATRIX_UNIFORM = "PROJECTION_MATRIX";
export const VIEW_MATRIX_UNIFORM = "VIEW_MATRIX";
export const MODEL_MATRIX_UNIFORM = "MODEL_MATRIX";
export const NORMAL_MATRIX_UNIFORM = "NORMAL_MATRIX";
export const CAMERA_POSITION_UNIFORM = "CAMERA_POSITION";
export const LIGHTS_UNIFORM = "LIGHTS";